// Send an "X submitted Y for booking Z" email with the rendered PDF attached
// each time a Job-Pack checklist lands. Best-effort: failures are logged but
// the worker's POST response isn't blocked, so a Resend hiccup doesn't cost
// the crew their submission.

const { sendEmail } = require('./email');
const { renderSubmissionPdf } = require('./jobPackPdf');

const FORM_HEADING = {
  vehicle_prestart:   '1. T&S Vehicle Pre-Start',
  risk_toolbox:       '2. Risk Assessment and Toolbox',
  tc_prestart:        '3. Traffic Controller Prestart Declaration',
  team_leader:        '4. Team Leader Checklist',
  post_shift_vehicle: '5. Post Shift Vehicle Checklist',
};

function defaultRecipients(db) {
  // Configurable via system_config.job_pack_notify_to. Falls back to
  // operations@tstc.com.au which the office asked for.
  try {
    const row = db.prepare("SELECT value FROM system_config WHERE key = 'job_pack_notify_to'").get();
    if (row && row.value) {
      return String(row.value).split(/[,;\s]+/).filter(Boolean);
    }
  } catch (_) { /* table may not exist on legacy DBs */ }
  return ['operations@tstc.com.au'];
}

async function notifySubmission(db, submissionId, opts) {
  const sub = db.prepare(`
    SELECT sf.*, cm.full_name AS crew_name,
      j.job_number, j.client AS job_client, j.job_name
    FROM safety_forms sf
    LEFT JOIN crew_members cm ON sf.crew_member_id = cm.id
    LEFT JOIN jobs j ON sf.job_id = j.id
    WHERE sf.id = ?
  `).get(submissionId);
  if (!sub) {
    console.error('[jobPackNotify] submission not found:', submissionId);
    return null;
  }
  const heading = FORM_HEADING[sub.form_type] || sub.form_type;
  const to = (opts && opts.to) || defaultRecipients(db);
  const submittedAt = new Date(sub.submitted_at).toLocaleString('en-AU', {
    timeZone: 'Australia/Sydney',
    weekday: 'long', day: 'numeric', month: 'long', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
  const baseUrl = process.env.APP_BASE_URL || 'https://tstc.up.railway.app';
  const reviewLink = `${baseUrl}/safety-forms/${sub.id}`;

  const subject = `[${heading}] ${sub.crew_name || 'Worker'}${sub.job_number ? ' — ' + sub.job_number : ''}`;
  const jobLine = sub.job_number
    ? `${sub.job_client || ''} — ${sub.job_number}${sub.job_name && sub.job_name !== sub.job_client ? ' — ' + sub.job_name : ''}`
    : '<em>Not bound to a job</em>';

  const html = `
    <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:#1F2937;font-size:14px;line-height:1.5;">
      <h2 style="color:#1D6AE5;margin:0 0 12px;">${heading}</h2>
      <p style="margin:0 0 14px;">A new ${heading.replace(/^\d\.\s*/, '')} has been submitted from the worker portal.</p>
      <table style="border-collapse:collapse;font-size:13px;">
        <tr><td style="color:#6B7280;padding:4px 12px 4px 0;">Submitted by</td><td style="font-weight:600;">${escapeHtml(sub.crew_name || '#' + sub.crew_member_id)}</td></tr>
        <tr><td style="color:#6B7280;padding:4px 12px 4px 0;">Date</td><td>${submittedAt}</td></tr>
        <tr><td style="color:#6B7280;padding:4px 12px 4px 0;vertical-align:top;">Booking</td><td>${jobLine}</td></tr>
        ${sub.signed_name ? `<tr><td style="color:#6B7280;padding:4px 12px 4px 0;">Signed name</td><td>${escapeHtml(sub.signed_name)}</td></tr>` : ''}
      </table>
      <p style="margin:18px 0 0;">A copy of the submission is attached as a PDF.</p>
      <p style="margin:8px 0 0;">
        <a href="${reviewLink}" style="display:inline-block;background:#1D6AE5;color:white;text-decoration:none;padding:8px 14px;border-radius:8px;font-weight:600;font-size:13px;">Review in the dashboard</a>
      </p>
      <p style="color:#9CA3AF;font-size:11px;margin-top:24px;">Auto-generated by T&S Operations — Job Pack notifications.</p>
    </div>
  `;

  let pdfBuf = null;
  try {
    pdfBuf = await renderSubmissionPdf(db, submissionId);
  } catch (e) {
    console.error('[jobPackNotify] PDF render failed:', e.message);
    // Send the email anyway — the link still works.
  }

  const dateSlug = new Date(sub.submitted_at).toISOString().slice(0, 10);
  const attachments = pdfBuf ? [{
    filename: `TSTC_${sub.form_type}_${dateSlug}_${sub.id}.pdf`,
    content: pdfBuf,
  }] : null;

  return sendEmail(to, subject, html, { attachments });
}

function escapeHtml(s) {
  if (s == null) return '';
  return String(s).replace(/[&<>"']/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]));
}

module.exports = { notifySubmission };
